"""
generate_synthetic_data.py
==========================
Generates a physics-inspired 4-D NetCDF file that the backend can load
without any internet connection.

Output: backend/data/sample_ocean_data.nc

Usage (from project root):
    python backend/scripts/generate_synthetic_data.py
"""

import sys
import os
import logging

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

# Resolve output path relative to this script's location
SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
BACKEND_DIR = os.path.dirname(SCRIPT_DIR)
OUTPUT_PATH = os.path.join(BACKEND_DIR, "data", "sample_ocean_data.nc")


def generate():
    import numpy as np
    import xarray as xr
    import pandas as pd

    logger.info("Building synthetic 4-D Indian Ocean dataset…")

    # ── Grid ──────────────────────────────────────────────────────────────
    lats   = np.linspace(-10, 30, 80)     # 40°N span, 0.5° resolution
    lons   = np.linspace(50, 100, 100)    # 50°E span, 0.5° resolution
    depths = np.array([0, 5, 10, 20, 30, 50, 75, 100, 150, 200, 300, 500, 1000], dtype=float)
    times  = pd.date_range("2026-08-28", periods=3, freq="D")

    T, D, La, Lo = len(times), len(depths), len(lats), len(lons)
    lon_g, lat_g = np.meshgrid(lons, lats)   # (La, Lo)

    rng  = np.random.default_rng(42)
    temp = np.zeros((T, D, La, Lo))

    for t in range(T):
        for d, dep in enumerate(depths):
            # Background gradient: warm surface → cold deep
            base   = 29.0 - (dep / 1000) * 22
            # Warm-core eddy centred at (10°N, 80°E)
            dist   = np.sqrt((lat_g - 10) ** 2 + (lon_g - 80) ** 2)
            eddy   = 4.5 * np.exp(-dist ** 2 / 180)
            # Arabian Sea cold upwelling near coast
            coast  = -1.5 * np.exp(-((lat_g - 15) ** 2 + (lon_g - 60) ** 2) / 50)
            # Seasonal signal
            season = 0.3 * np.sin(2 * np.pi * t / 365)
            noise  = rng.normal(0, 0.12, (La, Lo))
            temp[t, d] = base + eddy + coast + season + noise

    # Salinity: fresher near river outflows, saltier in the Arabian Sea
    salt = 35.2 - 0.04 * temp + rng.normal(0, 0.07, (T, D, La, Lo))
    salt = np.clip(salt, 28, 40)

    # Chlorophyll: surface peak, exponential decay with depth, higher in upwelling
    upwelling = np.exp(-((lat_g - 15) ** 2 + (lon_g - 62) ** 2) / 60)
    chl_base  = (0.15 + 0.6 * upwelling)[np.newaxis, np.newaxis, :, :]
    depth_decay = np.exp(-depths / 80)[:, np.newaxis, np.newaxis]  # (D,1,1) broadcast
    chl  = chl_base * depth_decay + rng.normal(0, 0.015, (T, D, La, Lo))
    chl  = np.clip(chl, 0.01, 8.0)

    # ── Build xarray Dataset ──────────────────────────────────────────────
    ds = xr.Dataset(
        {
            "temperature": (["time", "depth", "lat", "lon"], temp.astype("float32"),
                            {"units": "degC", "long_name": "Sea Water Temperature",
                             "standard_name": "sea_water_potential_temperature"}),
            "salinity":    (["time", "depth", "lat", "lon"], salt.astype("float32"),
                            {"units": "psu", "long_name": "Practical Salinity",
                             "standard_name": "sea_water_practical_salinity"}),
            "chlorophyll": (["time", "depth", "lat", "lon"], chl.astype("float32"),
                            {"units": "mg m-3", "long_name": "Chlorophyll-a Concentration",
                             "standard_name": "mass_concentration_of_chlorophyll_in_sea_water"}),
        },
        coords={
            "time":  times,
            "depth": (["depth"], depths, {"units": "m", "positive": "down"}),
            "lat":   (["lat"],   lats,   {"units": "degrees_north"}),
            "lon":   (["lon"],   lons,   {"units": "degrees_east"}),
        },
    )
    ds.attrs = {
        "title":        "OCEAN-X Synthetic Indian Ocean Dataset",
        "source":       "Physics-inspired synthetic data (offline demo)",
        "institution":  "OCEAN-X Hackathon",
        "Conventions":  "CF-1.8",
        "history":      "Generated by scripts/generate_synthetic_data.py",
    }

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    ds.to_netcdf(OUTPUT_PATH, encoding={
        "temperature": {"zlib": True, "complevel": 4},
        "salinity":    {"zlib": True, "complevel": 4},
        "chlorophyll": {"zlib": True, "complevel": 4},
    })
    logger.info(f"✅ Saved → {OUTPUT_PATH}")
    logger.info(f"   Grid: {T} times × {D} depths × {La} lats × {Lo} lons")
    logger.info(f"   Temp range: {float(temp.min()):.1f} – {float(temp.max()):.1f} °C")


if __name__ == "__main__":
    if os.path.exists(OUTPUT_PATH) and "--force" not in sys.argv:
        logger.info(f"Dataset already exists at {OUTPUT_PATH}")
        logger.info("Use --force to regenerate.")
    else:
        generate()
